name: CS challenge 
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Use github-tag-action to determine what the next tag version
    - uses: actions/checkout@master
    - name: Create version variable
      id: tag_version
      uses: anothrNick/github-tag-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}    

    # Maven, build and publish your application to GitHub packages
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
         java-version: '11'
         distribution: 'adopt'
    - name: Publish package
      run: mvn --batch-mode deploy
    
    # Use elgohr/Github-Release-Action to create a GitHub release
    - name: Create a GitHub release
      uses: elgohr/release-action@master
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

